version: "3.8"

services:
  weather-api:
    build: ./weather-api-go
    container_name: weather-api
    ports:
      - "8080:8080"
    volumes:
      - weather_data:/app/weather.db

volumes:
  weather_data: