openapi: 3.0.0
info:
  title: Weather API
  description: API for fetching weather updates and managing subscriptions.
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /weather:
    get:
      summary: Get weather data
      parameters:
        - name: city
          in: query
          required: true
          description: The name of the city to get the weather for.
          schema:
            type: string
      responses:
        '200':
          description: Successful response with weather data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WeatherResponse'
        '400':
          description: Bad request if city parameter is missing
  /subscribe:
    post:
      summary: Subscribe to weather updates
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscriptionRequest'
      responses:
        '201':
          description: Subscription created successfully
        '400':
          description: Bad request if the request body is invalid
  /unsubscribe:
    post:
      summary: Unsubscribe from weather updates
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscriptionRequest'
      responses:
        '204':
          description: Unsubscription successful
        '400':
          description: Bad request if the request body is invalid
components:
  schemas:
    WeatherResponse:
      type: object
      properties:
        city:
          type: string
        temp_c:
          type: number
          format: float
        weather:
          type: string
    SubscriptionRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        city:
          type: string
      required:
        - email
        - city